Script to get data from weather models + combine with station observation data

In [2]:
#Import required packages
from herbie import Herbie
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Get dates to get weather model data for (use dates for which we have station observation data points)
unique_dates = pd.to_datetime(pd.read_csv('mwobs_feature_data.csv')['date']).dt.date.unique()

In [4]:
#Format dates as strings
formatted_dates = []
for i in range(len(unique_dates)):
  formatted_dates.append(unique_dates[i].strftime("%Y-%m-%d") + " 10:00")

In [ ]:
#Gets forecast data from average of 6 100_km regions around Mt Washington as well as Mt Washington itself
def make_data_point(tempdata, dptdata, uwinddata, vwinddata, wspddata, precipdata, t800data, d800data, u800data, v800data, wspd800data):
  return np.array([tempdata[842, 1589].values,
  tempdata[842:842+30, 1589-33:1589].values.mean(),
  tempdata[842:842+30, 1589-66:1589-33].values.mean(),
  tempdata[842-30:842, 1589-33:1589].values.mean(),
  tempdata[842-30:842, 1589-66:1589-33].values.mean(),
  tempdata[842-30:842, 1589:1589+33].values.mean(),
  tempdata[842:842+30, 1589:1589+33].values.mean(),
  dptdata[842, 1589].values,
  dptdata[842:842+30, 1589-33:1589].values.mean(),
  dptdata[842:842+30, 1589-66:1589-33].values.mean(),
  dptdata[842-30:842, 1589-33:1589].values.mean(),
  dptdata[842-30:842, 1589-66:1589-33].values.mean(),
  dptdata[842-30:842, 1589:1589+33].values.mean(),
  dptdata[842:842+30, 1589:1589+33].values.mean(),
  uwinddata[842, 1589].values,
  uwinddata[842:842+30, 1589-33:1589].values.mean(),
  uwinddata[842:842+30, 1589-66:1589-33].values.mean(),
  uwinddata[842-30:842, 1589-33:1589].values.mean(),
  uwinddata[842-30:842, 1589-66:1589-33].values.mean(),
  uwinddata[842-30:842, 1589:1589+33].values.mean(),
  uwinddata[842:842+30, 1589:1589+33].values.mean(),
  vwinddata[842, 1589].values,
  vwinddata[842:842+30, 1589-33:1589].values.mean(),
  vwinddata[842:842+30, 1589-66:1589-33].values.mean(),
  vwinddata[842-30:842, 1589-33:1589].values.mean(),
  vwinddata[842-30:842, 1589-66:1589-33].values.mean(),
  vwinddata[842-30:842, 1589:1589+33].values.mean(),
  vwinddata[842:842+30, 1589:1589+33].values.mean(),
  wspddata[842, 1589].values,
  wspddata[842:842+30, 1589-33:1589].values.mean(),
  wspddata[842:842+30, 1589-66:1589-33].values.mean(),
  wspddata[842-30:842, 1589-33:1589].values.mean(),
  wspddata[842-30:842, 1589-66:1589-33].values.mean(),
  wspddata[842-30:842, 1589:1589+33].values.mean(),
  wspddata[842:842+30, 1589:1589+33].values.mean(),
  precipdata[842, 1589].values,
  precipdata[842:842+30, 1589-33:1589].values.mean(),
  precipdata[842:842+30, 1589-66:1589-33].values.mean(),
  precipdata[842-30:842, 1589-33:1589].values.mean(),
  precipdata[842-30:842, 1589-66:1589-33].values.mean(),
  precipdata[842-30:842, 1589:1589+33].values.mean(),
  precipdata[842:842+30, 1589:1589+33].values.mean(),
  t800data[842, 1589].values,
  t800data[842:842+30, 1589-33:1589].values.mean(),
  t800data[842:842+30, 1589-66:1589-33].values.mean(),
  t800data[842-30:842, 1589-33:1589].values.mean(),
  t800data[842-30:842, 1589-66:1589-33].values.mean(),
  t800data[842-30:842, 1589:1589+33].values.mean(),
  t800data[842:842+30, 1589:1589+33].values.mean(),
  d800data[842, 1589].values,
  d800data[842:842+30, 1589-33:1589].values.mean(),
  d800data[842:842+30, 1589-66:1589-33].values.mean(),
  d800data[842-30:842, 1589-33:1589].values.mean(),
  d800data[842-30:842, 1589-66:1589-33].values.mean(),
  d800data[842-30:842, 1589:1589+33].values.mean(),
  d800data[842:842+30, 1589:1589+33].values.mean(),
  u800data[842, 1589].values,
  u800data[842:842+30, 1589-33:1589].values.mean(),
  u800data[842:842+30, 1589-66:1589-33].values.mean(),
  u800data[842-30:842, 1589-33:1589].values.mean(),
  u800data[842-30:842, 1589-66:1589-33].values.mean(),
  u800data[842-30:842, 1589:1589+33].values.mean(),
  u800data[842:842+30, 1589:1589+33].values.mean(),
  v800data[842, 1589].values,
  v800data[842:842+30, 1589-33:1589].values.mean(),
  v800data[842:842+30, 1589-66:1589-33].values.mean(),
  v800data[842-30:842, 1589-33:1589].values.mean(),
  v800data[842-30:842, 1589-66:1589-33].values.mean(),
  v800data[842-30:842, 1589:1589+33].values.mean(),
  v800data[842:842+30, 1589:1589+33].values.mean(),
  wspd800data[842, 1589].values,
  wspd800data[842:842+30, 1589-33:1589].values.mean(),
  wspd800data[842:842+30, 1589-66:1589-33].values.mean(),
  wspd800data[842-30:842, 1589-33:1589].values.mean(),
  wspd800data[842-30:842, 1589-66:1589-33].values.mean(),
  wspd800data[842-30:842, 1589:1589+33].values.mean(),
  wspd800data[842:842+30, 1589:1589+33].values.mean(),
  ])

In [ ]:
#Get weather data for all dates, save files containing data
for group in np.arange(0, 3361, 30):
  all_data_points = []
  print(group)

  #Iterate through sets of 30 days
  for date in formatted_dates[group - 30:group]:
    print(date)
    try:
      H = Herbie(
          date,
          model="hrrr",
          product="sfc",
          fxx=10,
      )

      print('Collecting data...')
      #Get relevant fields from weather model - surface level
      tempdata = H.xarray(':TMP:2 m').t2m
      dptdata = H.xarray(':DPT:2 m').d2m
      uwinddata = H.xarray(':UGRD:10 m').u10
      vwinddata = H.xarray(':VGRD:10 m').v10
      wspddata = np.sqrt(uwinddata**2 + vwinddata**2)
      precipdata = H.xarray(':APCP:').tp

      Hprs = Herbie(
          date,
          model="hrrr",
          product="prs",
          fxx=10,
      )

      #Get relevant fields from weather model - 800mb level
      t800data = Hprs.xarray('TMP:800 mb').t
      d800data = Hprs.xarray('DPT:800 mb').dpt
      u800data = Hprs.xarray('UGRD:800 mb').u
      v800data = Hprs.xarray('VGRD:800 mb').v
      wspd800data = np.sqrt(u800data**2 + v800data**2)

      #Get data point from fields
      data_point = make_data_point(tempdata, dptdata, uwinddata, vwinddata, wspddata, precipdata, t800data, d800data, u800data, v800data, wspd800data)
      all_data_points.append(data_point)

    #If issue getting data, fill row with nans
    except:
      print("Error in getting data")
      all_data_points.append([np.nan for i in range(11*7)])

    #Save results once finished
  np.savetxt('model_data_v2' + str(group) + '.csv', np.array(all_data_points), delimiter = ',')

In [ ]:
#Concatenate files containing model data
df = pd.read_csv('model_data_v230.csv', header = None)
for i in range(60, 3361, 30):
  df = pd.concat([df, pd.read_csv('model_data_v2' + str(i) + '.csv', header = None)], axis = 0, ignore_index=True)

In [7]:
#Add datetime column
df.insert(0, 'datetime', pd.to_datetime(pd.Series(formatted_dates)))

In [8]:
#Rename columns
df.columns = ['datetime', 'tsfc1', 'tsfc2', 'tsfc3', 'tsfc4', 'tsfc5', 'tsfc6', 'tsfc7', 'tdsfc1', 'tdsfc2', 'tdsfc3', 'tdsfc4', 'tdsfc5', 'tdsfc6', 'tdsfc7', 'usfc1', 'usfc2', 'usfc3', 'usfc4', 'usfc5', 'usfc6', 'usfc7', 'vsfc1', 'vsfc2', 'vsfc3', 'vsfc4', 'vsfc5', 'vsfc6', 'vsfc7', 'wssfc1', 'wssfc2', 'wssfc3', 'wssfc4', 'wssfc5', 'wssfc6', 'wssfc7', 'psfc1', 'psfc2', 'psfc3', 'psfc4', 'psfc5', 'psfc6', 'psfc7', 't8001', 't8002', 't8003', 't8004', 't8005', 't8006', 't8007', 'td8001', 'td8002', 'td8003', 'td8004', 'td8005', 'td8006', 'td8007', 'u8001', 'u8002', 'u8003', 'u8004', 'u8005', 'u8006', 'u8007', 'v8001', 'v8002', 'v8003', 'v8004', 'v8005', 'v8006', 'v8007', 'ws8001', 'ws8002', 'ws8003', 'ws8004', 'ws8005', 'ws8006', 'ws8007']

In [9]:
#Load in feature data
mwobs_features = pd.read_csv('mwobs_feature_data.csv')
mwobs_features['date'] = pd.to_datetime(mwobs_features['date'])
mwobs_features.drop(columns = ['Unnamed: 0'], inplace=True)

In [10]:
mwobs_features

,date,M_5am,BL_5am,FG_5am,RA_5am,SN_5am,t_5am,dt_5am,rh_5am,ws_5am,...,FG_11pm,RA_11pm,SN_11pm,t_11pm,dt_11pm,rh_11pm,ws_11pm,vis_11pm,gust_11pm,wd_11pm
0,2014-08-01,True,False,False,False,False,44.6,42.8,93.35,23.0,...,True,False,False,44.6,44.6,100.00,27.0,0.00,27.0,W
1,2014-08-02,True,False,False,False,False,51.8,44.6,76.34,8.0,...,False,False,False,50.0,46.4,87.37,26.0,15.00,26.0,SW
2,2014-08-03,True,False,False,False,False,51.8,42.8,71.26,4.0,...,False,False,False,51.8,39.2,61.99,3.0,20.00,3.0,NE
3,2014-08-04,True,False,False,False,False,50.0,42.8,76.18,1.0,...,False,False,False,51.8,50.0,93.55,2.0,10.00,2.0,NW
4,2014-08-05,False,False,True,False,False,48.2,48.2,100.00,17.0,...,False,False,False,48.2,44.6,87.28,19.0,30.00,19.0,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,2024-04-06,False,False,True,False,True,12.2,12.2,100.00,27.0,...,True,False,True,14.0,14.0,100.00,27.0,0.06,30.0,N
3336,2024-04-07,False,False,True,False,False,14.0,14.0,100.00,27.0,...,True,False,True,12.2,12.2,100.00,34.0,0.06,34.0,N
3337,2024-04-08,True,False,False,False,False,23.0,10.4,57.96,33.0,...,False,False,False,23.0,-0.4,35.34,34.0,130.00,41.0,N
3338,2024-04-09,False,False,False,False,True,28.4,14.0,54.31,29.0,...,False,False,False,28.4,14.0,54.31,40.0,130.00,45.0,NW
3339,2024-04-10,True,False,False,False,False,30.2,23.0,74.26,29.0,...,False,False,False,33.8,17.6,51.04,23.0,100.00,23.0,W

In [13]:
#Reset index of filtered model data
df_shared = df
df_shared.reset_index(inplace=True, drop=True)

In [14]:
#Convert datetime to date (time is unnecessary)
df_shared['datetime'] = df_shared['datetime'].dt.date

In [16]:
#Concatenate model features with station observation features
all_features = pd.concat([df_shared, mwobs_features], axis = 1)
all_features.drop(columns = ['date'], inplace=True)

In [18]:
#Peform one-hot encoding on all non-numerical fields
all_features = pd.concat([all_features.iloc[:, 0], pd.get_dummies(all_features.iloc[:, 1:])], axis = 1)

In [19]:
#Print column labels
all_features.columns.values

array(['datetime', 'tsfc1', 'tsfc2', 'tsfc3', 'tsfc4', 'tsfc5', 'tsfc6',
       'tsfc7', 'tdsfc1', 'tdsfc2', 'tdsfc3', 'tdsfc4', 'tdsfc5',
       'tdsfc6', 'tdsfc7', 'usfc1', 'usfc2', 'usfc3', 'usfc4', 'usfc5',
       'usfc6', 'usfc7', 'vsfc1', 'vsfc2', 'vsfc3', 'vsfc4', 'vsfc5',
       'vsfc6', 'vsfc7', 'wssfc1', 'wssfc2', 'wssfc3', 'wssfc4', 'wssfc5',
       'wssfc6', 'wssfc7', 'psfc1', 'psfc2', 'psfc3', 'psfc4', 'psfc5',
       'psfc6', 'psfc7', 't8001', 't8002', 't8003', 't8004', 't8005',
       't8006', 't8007', 'td8001', 'td8002', 'td8003', 'td8004', 'td8005',
       'td8006', 'td8007', 'u8001', 'u8002', 'u8003', 'u8004', 'u8005',
       'u8006', 'u8007', 'v8001', 'v8002', 'v8003', 'v8004', 'v8005',
       'v8006', 'v8007', 'ws8001', 'ws8002', 'ws8003', 'ws8004', 'ws8005',
       'ws8006', 'ws8007', 'M_5am', 'BL_5am', 'FG_5am', 'RA_5am',
       'SN_5am', 't_5am', 'dt_5am', 'rh_5am', 'ws_5am', 'vis_5am',
       'gust_5am', 'M_11pm', 'BL_11pm', 'FG_11pm', 'RA_11pm', 'SN_11pm',
       't_11pm', 'dt_11pm', 'rh_11pm', 'ws_11pm', 'vis_11pm', 'gust_11pm',
       'wd_5am_E', 'wd_5am_N', 'wd_5am_NE', 'wd_5am_NW', 'wd_5am_S',
       'wd_5am_SE', 'wd_5am_SW', 'wd_5am_W', 'wd_11pm_E', 'wd_11pm_N',
       'wd_11pm_NE', 'wd_11pm_NW', 'wd_11pm_S', 'wd_11pm_SE',
       'wd_11pm_SW', 'wd_11pm_W'], dtype=object)

In [20]:
#Dename datetime column to date
newcols = ['date']
newcols.extend([i for i in all_features.columns[1:]])
all_features.columns = newcols

In [22]:
#Convert date to year month day features, drop date column
all_features.insert(0, 'year', pd.to_datetime(all_features['date']).dt.year)
all_features.insert(0, 'month', pd.to_datetime(all_features['date']).dt.month)
all_features.insert(0, 'day', pd.to_datetime(all_features['date']).dt.day)
all_features.drop(columns = ['date'], inplace=True)

In [23]:
#Convert booleans to floats (0 or 1)
all_features = all_features.astype(float)

In [24]:
#Print all column labels
all_features.columns.values

array(['day', 'month', 'year', 'tsfc1', 'tsfc2', 'tsfc3', 'tsfc4',
       'tsfc5', 'tsfc6', 'tsfc7', 'tdsfc1', 'tdsfc2', 'tdsfc3', 'tdsfc4',
       'tdsfc5', 'tdsfc6', 'tdsfc7', 'usfc1', 'usfc2', 'usfc3', 'usfc4',
       'usfc5', 'usfc6', 'usfc7', 'vsfc1', 'vsfc2', 'vsfc3', 'vsfc4',
       'vsfc5', 'vsfc6', 'vsfc7', 'wssfc1', 'wssfc2', 'wssfc3', 'wssfc4',
       'wssfc5', 'wssfc6', 'wssfc7', 'psfc1', 'psfc2', 'psfc3', 'psfc4',
       'psfc5', 'psfc6', 'psfc7', 't8001', 't8002', 't8003', 't8004',
       't8005', 't8006', 't8007', 'td8001', 'td8002', 'td8003', 'td8004',
       'td8005', 'td8006', 'td8007', 'u8001', 'u8002', 'u8003', 'u8004',
       'u8005', 'u8006', 'u8007', 'v8001', 'v8002', 'v8003', 'v8004',
       'v8005', 'v8006', 'v8007', 'ws8001', 'ws8002', 'ws8003', 'ws8004',
       'ws8005', 'ws8006', 'ws8007', 'M_5am', 'BL_5am', 'FG_5am',
       'RA_5am', 'SN_5am', 't_5am', 'dt_5am', 'rh_5am', 'ws_5am',
       'vis_5am', 'gust_5am', 'M_11pm', 'BL_11pm', 'FG_11pm', 'RA_11pm',
       'SN_11pm', 't_11pm', 'dt_11pm', 'rh_11pm', 'ws_11pm', 'vis_11pm',
       'gust_11pm', 'wd_5am_E', 'wd_5am_N', 'wd_5am_NE', 'wd_5am_NW',
       'wd_5am_S', 'wd_5am_SE', 'wd_5am_SW', 'wd_5am_W', 'wd_11pm_E',
       'wd_11pm_N', 'wd_11pm_NE', 'wd_11pm_NW', 'wd_11pm_S', 'wd_11pm_SE',
       'wd_11pm_SW', 'wd_11pm_W'], dtype=object)

In [25]:
#Find 11pm-5am change in all features, replace 11pm data with 6-hour 11pm-5am change
featurevars = ['M', 'BL', 'FG', 'RA', 'SN', 't', 'dt', 'rh', 'ws', 'vis', 'gust']
#Iterate through non-one-hot-encoded features, subtract 11PM (4UTC) from 5am (10UTC) data
for i in range(len(featurevars)):
  featurename = featurevars[i] + '_11pm'
  all_features[featurename] = all_features[featurevars[i] + '_5am'] - all_features[featurename]

dummies_5am = ['wd_5am_E', 'wd_5am_SE', 'wd_5am_S', 'wd_5am_SW', 'wd_5am_W', 'wd_5am_NW', 'wd_5am_N', 'wd_5am_NE']
dummies_11pm = ['wd_11pm_E', 'wd_11pm_SE', 'wd_11pm_S', 'wd_11pm_SW', 'wd_11pm_W', 'wd_11pm_NW', 'wd_11pm_N', 'wd_11pm_NE']
#Iterate through one-hot-encoded features, subtract 11PM (4UTC) from 5am (10UTC) data
for j in range(len(dummies_5am)):
  featurename = dummies_11pm[j]
  all_features[featurename] = all_features[dummies_5am[j]] - all_features[featurename]

In [26]:
#Rename columns to adjust for above change
new_cols = []
for col in all_features.columns:
  if '11pm' in col:
    new_cols.append(col.replace('11pm', '6hrchange'))
  else:
    new_cols.append(col)

all_features.columns = new_cols

In [29]:
#Add features containing spatial differences between adjacent model regions
#Count diagonal borders as adjacent
all_features.columns.values
#Lists containing first and second cells to calculate difference between
first = ['3', '3', '3', '2', '2', '2', '2', '7', '7']
second = ['2', '5', '4', '4', '5', '6', '7', '4', '6']
fields = ['tsfc', 'tdsfc', 'usfc', 'vsfc', 'wssfc', 'psfc', 't800', 'td800', 'u800', 'v800', 'ws800']
#Iterate through fields and pairs of cells, calculate differences and add as feature
for field in fields:
  for numidx in range(len(first)):
    all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])

C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])
C:\Users\benja\AppData\Local\Temp\ipykernel_14260\3161474453.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_features.insert(0, field + first[numidx] + second[numidx], all_features[field + first[numidx]] - all_features[field + second[numidx]])

In [30]:
all_features

,ws80076,ws80074,ws80027,ws80026,ws80025,ws80024,ws80034,ws80035,ws80032,v80076,...,wd_5am_SW,wd_5am_W,wd_6hrchange_E,wd_6hrchange_N,wd_6hrchange_NE,wd_6hrchange_NW,wd_6hrchange_S,wd_6hrchange_SE,wd_6hrchange_SW,wd_6hrchange_W
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-2.114274,-0.197411,-1.386205,-3.500478,-2.056756,-1.583615,-0.904934,-1.378075,0.678682,1.912058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.413929,-0.095486,1.460531,0.046602,-0.140648,1.365045,2.593176,1.087483,1.228131,1.281503,...,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0
4,-1.990047,-1.480498,1.476555,-0.513492,0.328568,-0.003943,1.023788,1.356299,1.027731,-0.251452,...,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,1.252909,0.902420,-1.392534,-0.139626,-2.537910,-0.490114,1.250670,-0.797125,1.740785,-0.610795,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3336,0.448587,0.703200,0.695516,1.144103,-1.060397,1.398716,1.904370,-0.554743,0.505654,-0.287499,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3337,2.419586,3.046813,-1.076736,1.342850,4.892933,1.970077,-0.984236,1.938621,-2.954312,-2.431503,...,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0
3338,-0.948465,4.114425,-5.016424,-5.964889,-1.743786,-0.901999,-0.657222,-1.499010,0.244777,1.351515,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3339,-0.900898,-1.015203,0.044999,-0.855899,1.311537,-0.970204,-4.310700,-2.028959,-3.340496,-0.762627,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0

In [31]:
#Save as CSV
#all_features.to_csv('all_feature_data.csv')